layers:
  - name: all
    dependencies:
      - fastapi
      - uvicorn
      - sqlalchemy
      - psycopg2-binary
      - passlib[bcrypt]
      - python-multipart
      - python-jose[cryptography]
      - python-dotenv
      - pydantic[email]
      - bitcoinlib
    files:
      - "*.py"
whitelist: []
